import Head from 'next/head';
import LoginHeader from '../components/loginHeader'


export default function Login() {
  return (
    <div>
        <Head>
            <title>Login | Purple</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <header>
          <LoginHeader pageName='Login'/>
        </header>

        <main>

        </main>

        <footer>
        
        </footer>
    </div>
  )
}
